services:
  stat_svc:
    build: ./stat_svc/http_service
    image: stat_svc
    container_name: stat_svc
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/stats
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=akhmed
  db:
    image: postgres:16.1
    container_name: db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_PASSWORD=akhmed
      - POSTGRES_USER=postgres
      - POSTGRES_DB=stats
