version: '3.1'
services:
  stat_svc:
    build: ./stat_svc/http_service
    image: stat_svc
    container_name: stat_svc
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/testdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=akhmed
  db:
    image: postgres:14-alpine
    container_name: stat-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_PASSWORD=akhmed
      - POSTGRES_USER=postgres
      - POSTGRES_DB=testdb

  main_svc:
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:14-alpine
